### ISSUE TITLE
Documentation for Non-W Pico Build Process

### ISSUE THREAD

**Issue by aaronsmithdev** [jasonfrowe/2600MultiCart#1]
Thanks for the awesome project! It's working perfectly on my 2600+. You're a lifesaver. I have an Uno Cart and was upset to find it didn't work on the 2600+. I started looking around for multi-cart options but found most of them were overly complex or didn't have a PCB. I ran across your earlier revision, was ready to build it, then you released this one! Awesome!

I did notice a couple issues with documentation during the build process, however, and wanted to pass them along (since they both have to do with documentation, I thought I'd wrap them into one issue).

1. The instructions seem to be specific to the Pico W. I built mine with a standard Pico and had to take a look at the Cmake list to find that the proper cmake command was: 

**cmake .. -DPICO_BOARD=pico**

2. After running cmake, I tried to run make and encountered this error:

_[  8%] Building C object CMakeFiles/pico_rom_wifi.dir/rom_wifi.c.obj
/home/aaron/2600/rom_wifi.c:17:10: fatal error: pico/cyw43_arch.h: No such file or directory
   17 | #include "pico/cyw43_arch.h" // Library for PICO_W_
   
  I found in the build list that the command I needed to run was:
  
  **make pico_rom**

After that, I had the UF2, flashed it to the Pico, and was able to play games without issue. I think dropping those couple notes in the documentation could save others some time (if everyone isn't using Pico W already). No other road bumps to speak of. It was super quick to assemble once the PCB came in and your instructions and code easy enough to work through to get to that resolution pretty easily.

I also plan on working on a case and will pass it along if you don't get to it first. If I do, I'll submit that as a pull request. Nice work! I appreciate you making it available to the community!

![PXL_20240229_234325408 PORTRAIT ORIGINAL](https://github.com/jasonfrowe/2600MultiCart/assets/82830826/a75de547-84ef-4b32-8e13-49cd68f320fb)

**Comment by jasonfrowe** [comment]
Thanks for the awesome feedback.  I will incorporate your suggestions into the documentation to help with others.  

Glad to hear the cart is working for you.  It's been a lot of fun so far.
